sessionSecret: "change-this-to-a-very-random-string"

discord:
  clientId: "1221092853531414660"
  clientSecret: "8zivFUfCMpvQQ0PWHw1tURSCeGJkvCFz"
  callbackUrl: "http://localhost:3000/api/auth/discord/callback"

pterodactyl:
  panelUrl: "https://panel.firecone.eu"
  adminApiKey: "ptla_OTgTmivmFmUapDTEDCxqp18OITg0EZhrKzZj31LT2WI"
  allowedNestId: 5

renewalHours: 24

plans:
  free:
    price: 0
    resources:
      cpu: 100
      memory: 1024
      disk: 5120
      ports: 1
      backups: 0
      databases: 0
    is24_7: false
    eggs: [1]
  basic:
    price: 50
    resources:
      cpu: 200
      memory: 2048
      disk: 10240
      ports: 1
      backups: 1
      databases: 1
    is24_7: true
    eggs: [1,2,3]

database:
  host: 5.249.164.28
  port: 5432
  user: pterodactyl
  password: Pl3453Ch4n63M3!
  name: niactylv1v

limits:
  maxServersPerUser: 3
  maxServersPerTeam: 10

# Proxy/VPN detection via proxycheck.io
proxycheck:
  apiKeys:
    - "YOUR_API_KEY_1"
    - "YOUR_API_KEY_2"
    # add more keys here
